# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish" # UNCOMMENT THIS LINE
baseURL = "https://dmpk.xyz/"
disableKinds = ['taxonomy', 'term']
defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
paginate = 10
summaryLength = 0

buildDrafts = false
buildFuture = false

#Â googleAnalytics = "G-XXXXXXXXX"

[imaging]
  anchor = 'Center'

#[taxonomies]
#  tag = "tags"
#  category = "categories"
#  author = "authors"
#  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]